### PR TITLE
clean snyk report

### PR DESCRIPTION
**Pull request by johnsall**
[STACS-Vulnerabilities]

#### 📲 What
Updating libs/deps according to the snyk report

#### 🤔 Why
		
To improve security
		
#### 🛠 How
		
Updated libs based on the report generated by `snyk test`

#### 👀 Evidence

image
		 
#### 🕵️ How to test

Just build

#### ✅ Acceptance criteria Checklist

- [ ] Code peer reviewed?
- [ ] Documentation has been updated to reflect the changes?
- [ ] Passing all automated tests, including a successful deployment?
- [ ] Passing any exploratory testing?
- [ ] Rebased/merged with latest changes from development and re-tested?
- [ ] Meeting the Coding Standards?

### CODE REVIEW

**Comment by ElvenSpellmaker** [comment]
Hey, what's the `Snyk.Fixes` folder for please?

**Comment by johnsall** [comment]
> 
> 
> Hey, what's the `Snyk.Fixes` folder for please?

Not sure, I think it's a byproduct of unsuccessful build attempts until I found the instructions. I've removed it. Also I'm looking to restore the line endings to CRLF instead of LS, as it creates unnecessary diffs

**Comment by ElvenSpellmaker** [comment]
> 
> 
> > Hey, what's the `Snyk.Fixes` folder for please?
> 
> Not sure, I think it's a byproduct of unsuccessful build attempts until I found the instructions. I've removed it. Also I'm looking to restore the line endings to CRLF instead of LS, as it creates unnecessary diffs

Thanks, also the files should all be LF, it's in the `.gitattributes` and was a conscious decision 🙂

**Comment by ElvenSpellmaker** [comment]
You'll see here we deliberately set LF: https://github.com/amido/stacks-dotnet/blob/master/.gitattributes#L1

**Comment by johnsall** [comment]
> 
> 
> > > Hey, what's the `Snyk.Fixes` folder for please?
> > 
> > 
> > Not sure, I think it's a byproduct of unsuccessful build attempts until I found the instructions. I've removed it. Also I'm looking to restore the line endings to CRLF instead of LS, as it creates unnecessary diffs
> 
> Thanks, also the files should all be LF, it's in the `.gitattributes` and was a conscious decision 🙂

Yes, the differences I was seeing was because of the extra folder, it's removed now, redid some updates, should be ok now. 
Still noob in .net and VS :P

**Comment by ElvenSpellmaker** [comment]
@johnsall No worries, thanks for doing the updates! 🙂

**Comment by ElvenSpellmaker** [comment]
Once this is merged in a PR will need to be made to `stacks-webapp-template` to update the SHA used by the Stacks CLI tool. I can show you how to do this after it's merged in if you'd like! 🙂

**Comment by johnsall** [comment]
> 
> 
> Once this is merged in a PR will need to be made to `stacks-webapp-template` to update the SHA used by the Stacks CLI tool. I can show you how to do this after it's merged in if you'd like! 🙂

yes please, I'm still feeling my way around stacs AND .net

**Comment by ElvenSpellmaker** [comment]
Thanks for this!

**Pull request merged**
